In [1]:
import numpy as np

In [2]:
lst=[[0,1,2,3,4,5,6,7,8],
     [9,10,11,12,13,14,15,16,17],
    [18,19,20,21,22,23,24,25,26],
    [27,28,29,30,31,32,33,34,35]]

In [3]:
print(type(lst))

<class 'list'>


In [4]:
arr=np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [7]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [8]:
arr3=np.random.rand(3,4)

In [9]:
arr3

array([[0.03994081, 0.06937196, 0.18260127, 0.5494977 ],
       [0.10844197, 0.83881625, 0.52887034, 0.63516094],
       [0.13859516, 0.79002064, 0.00101857, 0.24129051]])

In [10]:
arr[:,[1,2,3,0]]

array([[ 1,  2,  3,  0],
       [10, 11, 12,  9],
       [19, 20, 21, 18],
       [28, 29, 30, 27]])

### 

In [11]:
arr3+arr3

array([[0.07988162, 0.13874393, 0.36520254, 1.09899539],
       [0.21688394, 1.6776325 , 1.05774068, 1.27032189],
       [0.27719032, 1.58004127, 0.00203715, 0.48258102]])

In [12]:
arr3*arr3

array([[1.59526822e-03, 4.81246923e-03, 3.33432244e-02, 3.01947718e-01],
       [1.17596604e-02, 7.03612699e-01, 2.79703835e-01, 4.03429423e-01],
       [1.92086188e-02, 6.24132605e-01, 1.03749379e-06, 5.82211100e-02]])

In [13]:
arr[[0,2],[2,7]]

array([ 2, 25])

In [14]:
arr[:,::3]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [15]:
a=np.arange(15).reshape(5,3)

In [16]:
b=np.arange(10).reshape(2,5)

In [17]:
b@a

array([[ 90, 100, 110],
       [240, 275, 310]])

In [18]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [19]:
arr3d=np.arange(64).reshape(4,4,4)

In [20]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [21]:
arr3d[:,2,1:3] 
# 2d

array([[ 9, 10],
       [25, 26],
       [41, 42],
       [57, 58]])

In [22]:
arr3d[:,2:,1:3]
# 3d

array([[[ 9, 10],
        [13, 14]],

       [[25, 26],
        [29, 30]],

       [[41, 42],
        [45, 46]],

       [[57, 58],
        [61, 62]]])

In [23]:
np.ones(10)*12

array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr3d[:,:,:,2]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [26]:
arr3d[:,1,2]

array([ 6, 22, 38, 54])

In [27]:
arr[0:4,6:9]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [28]:
arr.ndim


2

In [29]:
arr.shape

(4, 9)

In [30]:
arr.ndim

2

In [65]:
ar=np.arange(25).reshape(5,5)

In [66]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
np.zeros_like(ar)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
print(arr[0:5])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [35]:
arr2=np.arange(19)

In [36]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [38]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [42]:
(arr2>3).sum()

15

In [44]:
(arr2>3)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr2d=np.array(lst2d)

In [49]:
arr2[arr2>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [50]:
arr2[arr2==5]

array([5])

In [51]:
arr2[arr2%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [141]:
arr2[arr2%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [142]:
lst=[[0,1,2,3,4,5,6,7,8],
     [9,10,11,12,13,14,15,16,17],
    [18,19,20,21,22,23,24,25,26],
    [27,28,29,30,31,32,33,34,35]]

In [143]:
arr2d=np.array(lst)

In [144]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [145]:
np.split(arr2d,3,axis=1)

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20],
        [27, 28, 29]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23],
        [30, 31, 32]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26],
        [33, 34, 35]])]

In [147]:
np.split(arr2d,2,axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [161]:
a=np.arange(12).reshape(4,3)

In [162]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [163]:
b=np.arange(0,3).reshape(1,3)


In [164]:
b

array([[0, 1, 2]])

In [165]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [174]:
x=np.array([[1],[2],[3]])
y=np.array([1,2,3])
z=np.broadcast(x,y)

In [175]:
z

In [167]:
arr2d[0,0]=0

In [111]:
arr3=arr2d*2

In [112]:
arr3

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [18, 20, 22, 24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46, 48, 50, 52],
       [54, 56, 58, 60, 62, 64, 66, 68, 70]])

In [62]:
arr2d[(arr2d>10)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [67]:
arr2d[(arr2d>10) & (arr2d<27)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [73]:
r=arr2d.ravel()

In [74]:
f=arr2d.flatten()

In [75]:
rs=arr2d.reshape(36)

In [78]:
print(r,f,rs)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [84]:
r[0]=1000

In [85]:
r

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35])

In [86]:
arr2d

array([[1000,    1,    2,    3,    4,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23,   24,   25,   26],
       [  27,   28,   29,   30,   31,   32,   33,   34,   35]])

In [88]:
f[0]=999

In [89]:
f

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35])

In [90]:
arr2d

array([[1000,    1,    2,    3,    4,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23,   24,   25,   26],
       [  27,   28,   29,   30,   31,   32,   33,   34,   35]])

In [91]:
rs[0]=888

In [92]:
rs

array([888,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35])

In [93]:
arr2d

array([[888,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35]])

In [122]:
ar1=np.arange(9).reshape(3,3)

In [123]:
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
ar2=np.arange(10,19).reshape(3,3)

In [1]:
ar2

NameError: name 'ar2' is not defined

In [131]:
dstack=np.dstack((ar1,ar2))

In [132]:
dstack

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]]])

In [ ]:
lst2d=[[1,2,3],[4,5,6]]

In [ ]:
arr2d=np.array(lst2d)

## 

In [ ]:
arr2d(2,5)

In [ ]:
arr2d